#!/bin/sh
# définit le répertoire AppImage comme racine
HERE="$(dirname "$(readlink -f "$0")")"
export PATH="$HERE/usr/bin:$PATH"
export LD_LIBRARY_PATH="$HERE/usr/lib:$LD_LIBRARY_PATH"

# vérifie que pcscd est lancé
if ! pgrep -x pcscd >/dev/null; then
    echo "Démarrage du daemon PC/SC..."
    systemctl start pcscd || echo "Impossible de démarrer pcscd"
fi

# lance ton binaire Python (PyInstaller)
exec "$HERE/bin/CARTEIDLECTEUR" "$@"
